services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flix_frontend_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      API_URL: ${API_URL:-http://backend:3000/api}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
    ports:
      - '${FRONTEND_PORT:-3001}:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev

